---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: enable
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
